### PR TITLE
homepage responsive tweaks

### PR DESCRIPTION
**Pull request by kitsandkats**

### CODE REVIEW

**Comment by yourcelf** [comment]
Hey, these changes generally look good; thanks for fixing.  The fixes to backgrounds in the menu etc. are urgent and great.  I'm a little less excited about changing the breakpoints for responsive widths.

For the breakpoint changes, I'm worried about maintainability.  First, there's a chance you've missed some responsive parts in bootstrap that respond to the old @media break-points, and which will now behave in hard-to-predict ways since different parts of the page break at different points.  Second, it'll be difficult to upgrade bootstrap, as we'll have shadowed/overridden some core class types.

If we need to change break-points, I'd be happier if we generate our own custom bootstrap build with different starting variables for the breakpoints (see http://getbootstrap.com/customize/).  That way, if we upgrade bootstrap, we can just recompile with our changed variables and know that everything should be good again.

But a second point: if the only reason we're changing the media breakpoints is because long usernames can be too long, I'd rather fix that by limiting the width of the username display.  That's because ultra-long usernames can still break it...
screenshot from 2015-01-15 14 30 51
...and because it makes things complicated.

A simpler approach we could take there is to do a max-width with overflow ellipsis:
screenshot from 2015-01-15 14 32 37

Style to get that:

    #user-menu-label {
        ... other styles ...
        max-width: 200px;
        text-overflow: ellipsis;
        overflow: hidden;
        white-space: nowrap;
    }
 
Here are three other existing bugs that you didn't create or fix, but which we could fix in this or a future rev:

 - /events/ (md size): past events doesn't clear upcoming unless there are an even number of events. Current production has the same problem, so you didn't introduce it:
screenshot from 2015-01-15 14 17 55

 - /events/ doesn't seem to be loading bootstrap javascript, so the collapsed menubar doesn't work there.

 - Username submenu shows up in a weird place, and event settings submenu doesn't work right, on anything below md on event pages (this is also seriously borked in the current production master, so it at least is no worse in this changeset):
screenshot from 2015-01-15 14 20 26

**Comment by yourcelf** [comment]
One other minor nitpick: there are several places in the templates where we have class lists like:

   <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>...</div>

The duplicated listing there is unnecessary.  The above is exactly equivalent to:

    <div class='col-xs-12'></div>

If there isn't a style given for a particular col size ("xs", "sm", "md", "lg"), the browser will use the next smallest given style.  So every place where you see adjacent col classes with the same number of cols, you can remove the larger one, leaving the templates more readable and the css parsing a little simpler.

And one more existing responsive width bug that your changeset didn't create or fix: the previous videos list renders not nicely in sizes below "lg":
screenshot from 2015-01-15 14 44 09

**Comment by yourcelf** [comment]
(BTW, I'm happy to merge this now if you like -- the above are all opinion/advisory more than blocking concerns).

**Comment by kitsandkats** [comment]
Thanks for the feedback, Charlie! 

I agree about the modification of breakpoints. I was also thinking that we should do a custom bootstrap build, particularly for the lobby layout/responsiveness, though the standard bootstrap should be fine for everything else. I'm happy to start thinking about this. 

But for now, I'll remove the breakpoint modifications from this, and fix the username issue as you suggested. I'm also happy to take a look at the other bugs you mentioned.

**Comment by kitsandkats** [comment]
hey @yourcelf, let me know what you think of these most recent changes. I didn't dive into anything on the event pages, as I think we might want to consider a custom bootstrap build for those.

**Comment by yourcelf** [comment]
Hey @kitsandkats, I haven't had a chance to try it running locally yet, but things look great from the diff.  If you feel confident with these changes, I'm happy to merge.  I can do a more thorough evaluation early next week -- but I think regardless we're on balance fixing more bugs than we're introducing with this change set, so I'm comfortable doing it.

**Comment by kitsandkats** [comment]
Either way works for me. I don't foresee any problems, but there's also no rush with these changes.

**Comment by kitsandkats** [comment]
Hey @yourcelf , let me know if there is anything else that needs to be fixed before this change set can be merged!

**Comment by yourcelf** [comment]
Sorry for delay. Merging!

**Pull request merged**
