### PR TITLE
add hangout/local-gadget.xml path

### PR DESCRIPTION
**Pull request by thehunmonkgroup**
allows a public server to serve a gadget.xml file for local development.

Regarding using the public unhangout facilitator hangout plugin, DEVELOPMENT.md says: "It should work with any installation equally well, since clients provide it the unhangout server host they connected from on load."

As far as I can tell, this is not the case. The project ID for the facilitator plugin is passed to the hangout, which loads the plugin from the Application URL specified in the Hangouts API configuration for the project. If a facilitator plugin is hosted at /hangout/gadget.xml on server A, and server B uses the project ID that points to /hangout/gadget.xml hosted on server A, I see no way that server A can know the whereabouts of server B when it builds the baseUrl for the gadget.

Fortunately, outside of some hoop jumping to get permissions to make hangout gadgets publicly accesible, creating a new project and pointing its Application URL to /hangout/gadget.xml on a custom unhangout installation is fairly trivial. If, however, a person deploying an unhangout installation wants to have the facilitator app load for localhost development, the same issue emerges. And, simply creating another project and pointing its Application URL to https://localhost/hangout/gadget.xml doesn't work, either, as it appears that all plugins must be hosted on a publicly available server.

All of that to say this: this pull request works around the apparent lack of localhost development support by:

 - Introducing an UNHANGOUT_LOCALHOST_PORT config parameter, set to the port unhangout uses on a localhost development environment
 - Introducing a /hangout/local-gadget.xml path, which will build the baseUrl for the facilitator plugin in the following form: http(s)://localhost:[UNHANGOUT_LOCALHOST_PORT]
 
From there, with a production server at example.com, two Google projects can be created, each using one of the following two Application URLs for the Hangout API:

 - https://example.com/hangout/gadget.xml
 - https://example.com/hangout/local-gadget.xml
 
Developers then run their localhost installation at UNHANGOUT_LOCALHOST_PORT, and use the project ID that points to the local-gadget.xml Application URL.

All of this feels kind of clunky, and, it works in my testing. If I'm missing something, and/or there's a better way to do it, I'm all ears.

In the meantime, please consider this pull request. I'm open to refactoring the code to suit your guidelines -- this was a first attempt at decent abstraction to solve the problem. Note that I would have preferred to put the baseUrl function in lib/utils.js, but that creates a circular dependency with lib/options.js, so I just tossed it in its own file for now.

### CODE REVIEW

**Comment by yourcelf** [comment]
Hey,  Sorry for my delay in replying.  The way we've been testing the hangout gadget locally is to short-circuit google entirely, and just use a local path.  In development, the route [``/test/hangout/:sessionId``](https://github.com/drewww/unhangout/blob/f3a1ae481ef1f1171cc7f4ff9e06fb4e26be32cc/lib/unhangout-routes.js#L904) maps to a mockup of the Google Hangout app environment which runs the app.  Links to join hangout sessions from events also redirect to there rather than actual Google in development.

This is obviously not as thorough as running the app for real on Google servers as you propose, but it's much simpler, and doesn't require setting up additional Hangout API endpoints.  In our experience so far, it's been adequate for developing the gadget.

Does this work for the needs you have?  Clearly we need to document this better.  I agree that the solution you have here is a bit clunky and confusing, so if the simpler local/mocked environment is adequate, I'd prefer to stick to that.  But if there's a compelling need to have the app run in actual Google during development I'll consider merging.

**Comment by thehunmonkgroup** [comment]
Hey, thanks for replying -- I was beginning to think there was no one home over there, and then I had my own delay in getting back to you! At least forward progress is happening... ;)

I think using the mockup is fine, and, when I tried it, the socket messaging wasn't working -- which seems like an important thing for the mock to have, to test, for example, sending messages to sessions.

So I refactored my approach to get that working instead. This is certainly much simpler, and it advances the capability of the existing mockup.

My original idea is still in the commit history for the branch, in case we ever want to revisit.

Let me know what you think...

**Comment by yourcelf** [comment]
This looks great.  We'll need to fix the [test failures](https://travis-ci.org/drewww/unhangout/builds/59146232) before I can merge.  It looks like it's mostly just issues with changed logic for getting the hangout URL.  I don't have time to fix these today, but will try to find time to look at them this week if you don't get to it first.

**Comment by yourcelf** [comment]
Thanks, got tests fixed and made one minor change to quote the regexp for the base URL and merged.

**Pull request merged**
